apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pvc
  namespace: three-tier-app
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp2-immediate
  resources:
    requests:
      storage: 2Gi

