apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: three-tier-app
type: Opaque
data:
  DB_USER: Ym1pX3VzZXI=             # Base64 encoded value
  DB_PASSWORD: YWRtaW4xMjM0         # Base64 encoded value
  DB_NAME: Ym1pX2Ri                 # Base64 encoded value